
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 554984
	#The name of the modpack
	modpackName = "Woods Of The Past"
	#The version of the modpack
	modpackVersion = "5.3"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

