
[General]
	DEBUG = true

	[General.Compat]
		Immersive_Engineering = true
		Pams_Harvestcraft = true
		#A config file will be generated when the mod is loaded while the feature is enabled. 
		#If you disable a feature the config file and block registration/generation will be disabled
		Minecraft = true

	[General.Global_Modifier]
		#Global generation patch size modifier (higher is more) [Default: 5]
		Size = 2
		#Global generation frequency modifier (higher is more) [Default: 1]
		Frequency = 1

