
["The Crop Reaping Mod"]
	#Requires seeds for auto planting?  Default: false
	#eg: If you harvest carrots, then you must have carrots in your inventory to auto-re-plant
	requiresSeeds = false
	#When player reaps a crop, the drops go straight into inventory?  Default: true
	giveDropsToPlayer = true

