
#Valid Biome Types:
#Temperature: [HOT, COLD] 
#Vegetation: [SPARSE, DENSE] 
#Humidity: [WET, DRY] 
#Tree Types: [SAVANNA, CONIFEROUS, JUNGLE] 
#Attributes: [SPOOKY, DEAD, LUSH, MUSHROOM, MAGICAL, RARE, PLATEAU, MODIFIED, OCEAN, RIVER, WATER] 
#Generic Types: [MESA, FOREST, PLAINS, MOUNTAIN, HILLS, SWAMP, SANDY, SNOWY, WASTELAND, BEACH, VOID] 
#Use: [OVERWORLD] to generate in all biomes
["MINECRAFT_WILD WHEAT"]
	"Enabled:" = true
	#Default: [SAVANNA]
	"Biome Type:" = "SAVANNA"
	#Default [1]
	"Frequency:" = 1
	#Default [1]
	"Patch Size:" = 1

["MINECRAFT_WILD CARROTS"]
	"Enabled:" = true
	#Default: [PLAINS]
	"Biome Type:" = "PLAINS"
	#Default [1]
	"Frequency: " = 1
	#Default [1]
	"Patch Size: " = 1

["MINECRAFT_WILD POTATOES"]
	"Enabled:" = true
	#Default: [PLAINS]
	"Biome Type:" = "PLAINS"
	#Default [1]
	"Frequency:" = 1
	#Default [1]
	"Patch Size:" = 1

["MINECRAFT_WILD BEETROOTS"]
	"Enabled:" = true
	#Default: [PLAINS]
	"Biome Type:" = "PLAINS"
	#Default [1]
	"Frequency:" = 1
	#Default [1]
	"Patch Size:" = 1

